### ISSUE TITLE
build on OS X 10.10.3 error

### ISSUE THREAD

**Issue by rowanblaik** [mapillary/OpenSfM#26]
Hello,

I've followed the steps to install dependencies via brew but cannot get the build step to work. Here is the error message from the terminal:

``Configuring...
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    subprocess.Popen(['cmake','../opensfm/src'], cwd='cmake_build').wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory``

Many thanks in advance!

**Comment by paulinus** [comment]
It looks like subprocess is not finding the `cmake` command. Is cmake installed?

**Comment by rowanblaik** [comment]
You're right. Thank you very much for the quick reply. I installed cmake via brew and the build script runs. It flags up this error about cfsm now:

``MACOSX_RPATH is not specified for the following targets:
csfm``

Running the example gives this:

``Extracting focal lengths for image 01.jpg
Extracting focal lengths for image 02.jpg
Extracting focal lengths for image 03.jpg
Traceback (most recent call last):
  File "/Users/rowan/Desktop/OpenSfM-master/bin/detect_features", line 10, in <module>
    from opensfm import features
  File "/Users/rowan/Desktop/OpenSfM-master/opensfm/features.py", line 12, in <module>
    import csfm
ImportError: No module named csfm``

**Comment by paulinus** [comment]
The MACOSX_RPATH warning is normal. It should be no problem. Could you paste the complete build log?

**Comment by rowanblaik** [comment]
```
Configuring...
-- The C compiler identification is AppleClang 6.1.0.6020049
-- The CXX compiler identification is AppleClang 6.1.0.6020049
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS) 
-- Looking for dgemm_
-- Looking for dgemm_ - found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- A library with BLAS API found.
-- Found AMD library: /usr/local/lib/libamd.a
-- Found AMD header in: /usr/local/include
-- Found CAMD library: /usr/local/lib/libcamd.a
-- Found CAMD header in: /usr/local/include
-- Found COLAMD library: /usr/local/lib/libcolamd.a
-- Found COLAMD header in: /usr/local/include
-- Found CCOLAMD library: /usr/local/lib/libccolamd.a
-- Found CCOLAMD header in: /usr/local/include
-- Found CHOLMOD library: /usr/local/lib/libcholmod.a
-- Found CHOLMOD header in: /usr/local/include
-- Found SuiteSparseQR library: /usr/local/lib/libspqr.a
-- Found SuiteSparseQR header in: /usr/local/include
-- Found Intel Thread Building Blocks (TBB) library: /usr/local/lib/libtbb.dylib, assuming SuiteSparseQR was compiled with TBB.
-- Found Intel Thread Building Blocks (TBB) Malloc library: /usr/local/lib/libtbbmalloc.dylib
-- Found SuiteSparse_config library: /usr/local/lib/libsuitesparseconfig.a
-- Found SuiteSparse_config header in: /usr/local/include
-- Did not find METIS library (optional SuiteSparse dependency)
-- Found SuiteSparse: TRUE (found version "4.2.1") 
-- Found Eigen: /usr/local/include/eigen3 (found version "3.2.4") 
-- Found ceres: /usr/local/lib/libceres.dylib  
-- Found Gflags: /usr/local/include  
-- Found Glog: /usr/local/include  
-- Could NOT find Boost
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found version "2.7.6") 
-- Found PythonInterp: /usr/bin/python2.7 (found version "2.7.6") 
-- Found NumPy: version "1.9.2" /usr/local/lib/python2.7/site-packages/numpy/core/include
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   csfm

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/rowan/desktop/OpenSfM-master/cmake_build
Compiling extension...
Scanning dependencies of target vl
Scanning dependencies of target akaze
Scanning dependencies of target mv
[  2%] [  4%] Building CXX object CMakeFiles/akaze.dir/third_party/akaze/lib/fed.cpp.o
Building CXX object CMakeFiles/akaze.dir/third_party/akaze/lib/AKAZE.cpp.o
[  6%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/aib.c.o
In file included from /Users/rowan/desktop/OpenSfM-master/opensfm/src/third_party/akaze/lib/fed.cpp:33:
In file included from /Users/rowan/desktop/OpenSfM-master/opensfm/src/third_party/akaze/lib/fed.h:22:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:265:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__bit_reference:15:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:628:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:604:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:341:10: fatal error: '__debug' file not found
#include <__debug>
         ^
[  8%] Building CXX object CMakeFiles/mv.dir/third_party/libmv/multiview/fundamental.cc.o
In file included from /Users/rowan/desktop/OpenSfM-master/opensfm/src/third_party/akaze/lib/AKAZE.cpp:23:
In file included from /Users/rowan/desktop/OpenSfM-master/opensfm/src/third_party/akaze/lib/AKAZE.h:12:
In file included from /Users/rowan/desktop/OpenSfM-master/opensfm/src/third_party/akaze/lib/AKAZEConfig.h:12:
In file included from /usr/local/include/opencv2/opencv.hpp:47:
In file included from /usr/local/include/opencv2/core/core.hpp:56:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:628:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:604:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:341:10: fatal error: '__debug' file not found
#include <__debug>
         ^
In file included from /Users/rowan/desktop/OpenSfM-master/opensfm/src/third_party/libmv/multiview/fundamental.cc:21:
In file included from /Users/rowan/desktop/OpenSfM-master/opensfm/src/third_party/libmv/multiview/fundamental.h:24:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/vector:265:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__bit_reference:15:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:628:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:604:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:341:10: fatal error: '__debug' file not found
#include <__debug>
         ^
[ 10%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/array.c.o
[ 12%] 1 error generated.
Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/covdet.c.o
make[2]: *** [CMakeFiles/akaze.dir/third_party/akaze/lib/fed.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 14%] Building CXX object CMakeFiles/mv.dir/third_party/libmv/multiview/projection.cc.o
In file included from /Users/rowan/desktop/OpenSfM-master/opensfm/src/third_party/libmv/multiview/projection.cc:21:
In file included from /Users/rowan/desktop/OpenSfM-master/opensfm/src/third_party/libmv/multiview/projection.h:24:
In file included from /Users/rowan/desktop/OpenSfM-master/opensfm/src/third_party/libmv/numeric/numeric.h:28:
In file included from /usr/local/include/eigen3/Eigen/Cholesky:4:
In file included from /usr/local/include/eigen3/Eigen/Core:28:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/complex:247:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/sstream:174:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/ostream:131:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/ios:216:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__locale:15:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string:439:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:628:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:604:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:341:10: fatal error: '__debug' file not found
#include <__debug>
         ^
[ 16%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/dsift.c.o
/Users/rowan/desktop/OpenSfM-master/opensfm/src/third_party/vlfeat/vl/dsift.c:265:26: warning: using floating point absolute value function 'fabsf' when argument is of integer
      type [-Wabsolute-value]
    *kerIter++ = (1.0F - fabsf(x) / binSize) *
                         ^
/Users/rowan/desktop/OpenSfM-master/opensfm/src/third_party/vlfeat/vl/dsift.c:265:26: note: use function 'abs' instead
    *kerIter++ = (1.0F - fabsf(x) / binSize) *
                         ^~~~~
                         abs
1 warning generated.
[ 18%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/fisher.c.o
[ 20%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/generic.c.o
[ 22%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/getopt_long.c.o
[ 24%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/gmm.c.o
1 error generated.
make[2]: *** [CMakeFiles/akaze.dir/third_party/akaze/lib/AKAZE.cpp.o] Error 1
make[1]: *** [CMakeFiles/akaze.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 26%] Building CXX object CMakeFiles/mv.dir/third_party/libmv/multiview/five_point.cc.o
In file included from /Users/rowan/desktop/OpenSfM-master/opensfm/src/third_party/libmv/multiview/five_point.cc:21:
In file included from /Users/rowan/desktop/OpenSfM-master/opensfm/src/third_party/libmv/multiview/five_point.h:24:
In file included from /Users/rowan/desktop/OpenSfM-master/opensfm/src/third_party/libmv/base/vector.h:31:
In file included from /usr/local/include/eigen3/Eigen/Core:28:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/complex:247:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/sstream:174:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/ostream:131:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/ios:216:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__locale:15:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string:439:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:628:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:604:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:341:10: fatal error: '__debug' file not found
#include <__debug>
         ^
[ 28%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/hikmeans.c.o
[ 30%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/hog.c.o
[ 32%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/homkermap.c.o
[ 34%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/host.c.o
[ 36%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/ikmeans.c.o
[ 38%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/imopv.c.o
[ 40%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/imopv_sse2.c.o
[ 42%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/kdtree.c.o
[ 44%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/kmeans.c.o
1 error generated.
make[2]: *** [CMakeFiles/mv.dir/third_party/libmv/multiview/projection.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 46%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/lbp.c.o
[ 48%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/liop.c.o
[ 50%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/mathop.c.o
[ 52%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/mathop_avx.c.o
[ 54%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/mathop_sse2.c.o
[ 56%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/mser.c.o
[ 58%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/pgm.c.o
[ 60%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/quickshift.c.o
/Users/rowan/desktop/OpenSfM-master/opensfm/src/third_party/vlfeat/vl/pgm.c:236:18: warning: comparison of constant 65536 with boolean expression is always false
      [-Wtautological-constant-out-of-range-compare]
  if(! max_value >= 65536) {
     ~~~~~~~~~~~ ^  ~~~~~
1 warning generated.
[ 62%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/random.c.o
[ 64%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/rodrigues.c.o
[ 66%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/scalespace.c.o
[ 68%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/sift.c.o
[ 70%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/slic.c.o
[ 72%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/stringop.c.o
[ 74%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/svm.c.o
[ 76%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/svmdataset.c.o
[ 78%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/vlad.c.o
Linking C static library libvl.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libvl.a(mathop_avx.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libvl.a(mathop_avx.c.o) has no symbols
[ 78%] Built target vl
1 error generated.
make[2]: *** [CMakeFiles/mv.dir/third_party/libmv/multiview/five_point.cc.o] Error 1
1 error generated.
make[2]: *** [CMakeFiles/mv.dir/third_party/libmv/multiview/fundamental.cc.o] Error 1
make[1]: *** [CMakeFiles/mv.dir/all] Error 2
make: *** [all] Error 2
Building package
running build
running build_py
creating build
creating build/lib
creating build/lib/opensfm
copying opensfm/__init__.py -> build/lib/opensfm
copying opensfm/context.py -> build/lib/opensfm
copying opensfm/dataset.py -> build/lib/opensfm
copying opensfm/exif.py -> build/lib/opensfm
copying opensfm/features.py -> build/lib/opensfm
copying opensfm/geo.py -> build/lib/opensfm
copying opensfm/geotag_from_gpx.py -> build/lib/opensfm
copying opensfm/io.py -> build/lib/opensfm
copying opensfm/matching.py -> build/lib/opensfm
copying opensfm/mesh.py -> build/lib/opensfm
copying opensfm/multiview.py -> build/lib/opensfm
copying opensfm/reconstruction.py -> build/lib/opensfm
copying opensfm/sensors.py -> build/lib/opensfm
copying opensfm/transformations.py -> build/lib/opensfm
copying opensfm/video.py -> build/lib/opensfm
creating build/lib/opensfm/data
copying opensfm/data/sensor_data.json -> build/lib/opensfm/data
```

**Comment by paulinus** [comment]
The problem seems to be a missing `__debug` header in Command Line Tools 6.3.  In [this thread](https://github.com/Homebrew/homebrew/issues/38514) people propose to install Xcode to solve the issue, or wait for Apple to fix CLT

**Comment by rowanblaik** [comment]
Thanks for the confirmation. I'll wait for Apple to fix it then try again

**Comment by slhck** [comment]
There's an Apple software update available now that should fix it.

**Comment by sahilshah** [comment]
@slhck I am getting this exact same error. However, even after the Applt CLT update this isn't fixed. Any ideas? Thanks!

**Comment by sahilshah** [comment]
@rowanblaik @slhck I think this problem is due to the absence of operating code in 2 files in the 3rd party libs. I added a function that effectively did nothing to the 2 files causing this error and then I was able to build.

**Comment by rowanblaik** [comment]
Did the built binary function properly? Could you guide me how to achieve that too please?

**Comment by sahilshah** [comment]
It did function properly. However, I had to build boost from source as well because brew did not build libboost_python for some reason even though I used appropriate flags. 
You can add something like `void test(){ int x; x = 0; }` in both the files that are not getting compiled for libmv and libvl. I read somewhere on the internet that its because the files don't have any operating code.

**Comment by rowanblaik** [comment]
Just a quick note to say that the build is working with the recent CLT update. Many thanks!
