### ISSUE TITLE
CMakeLists.txt libboost_python.a

### ISSUE THREAD

**Issue by lukebaumann** [mapillary/OpenSfM#39]
127     target_link_libraries(csfm "${Boost_LIBRARY_DIR}/libboost_python.a")

should be

127     target_link_libraries(csfm "${Boost_LIBRARY_DIRS}/libboost_python.a")

otherwise it will not complete setup.py

**Comment by paulinus** [comment]
hi, i've just updated cmake to use the default Boost Python library (https://github.com/mapillary/OpenSfM/commit/85e6a95714baa3cbf0e4535c0f57af996fb3cb19), which should solve this problem.

It will also link to the shared library instead of the static one.

thanks

**Comment by gilbert1991** [comment]
This problem is not fixed for opengv, please note it in README

**Comment by paulinus** [comment]
answering on opengv's issue https://github.com/laurentkneip/opengv/issues/27
